# Site settings
# title: Scifidelity Orchestra
description: 'Jazz that makes you want to dance!'
description1: 'info@scifidelityorchestra.com'
description2: '+385 91 54 88 101'
#url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Info'
  email: info@scifidelityorchestra.com
#  twitter_username: joshgerdes
  facebook_username: scifidelityorchestra
  github_username:  schef/scifidelityorchestra
#  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
